p = input("digite algo: ")
print('o tipo primitivo desse valor e? ',type(p))
print('Só tem espaço?', p.isspace())
print('É um número? ', p.isnumeric())
print('É um alfanúmerico? ', p.isalnum())
print('É um alfabético?', p.isalpha())
print('Esta em maiúsculas?', p.isupper())
print('Esta em minúsculas?', p.islower())
print('Está captalizada?', p.istitle())
